export const PlayerState = {
    NONE: 'NONE',
    RECORDING: 'START_VIDEO_RECORDING',
    PREVIEW: 'VIDEO_SAVED',
    START_AUDIO_RECORDING: 'START_AUDIO_RECORDING',
    STOP_AUDIO_RECORDING: 'STOP_AUDIO_RECORDING',
    SAVED: 'AUDIO_VIDEO_SAVED'
};
