export const PlayerState = {
    NONE: 'NONE',
    START_VIDEO_RECORDING: 'START_VIDEO_RECORDING',
    VIDEO_SAVED: 'VIDEO_SAVED',
    START_AUDIO_RECORDING: 'START_AUDIO_RECORDING',
    STOP_AUDIO_RECORDING: 'STOP_AUDIO_RECORDING',
    AUDIO_VIDEO_SAVED: 'AUDIO_VIDEO_SAVED'
};
